export const subcaseSchema = {
  type: 'object',
  required: ['namespace', 'name', 'version'],
  properties: {
    namespace: {
      type: 'string',
      'x-group': 'Identity',
      'x-order': 0,
    },
    name: {
      type: 'string',
      'x-group': 'Identity',
      'x-order': 1,
    },
    version: {
      type: 'string',
      'x-group': 'Configuration',
      'x-order': 10,
    },
    completionStrategy: {
      type: 'string',
      enum: ['DEFAULT', 'CUSTOM'],
      'x-group': 'Configuration',
      'x-order': 11,
    },
    waitForCompletion: {
      type: 'boolean',
      'x-group': 'Configuration',
      'x-order': 12,
    },
    inputMapping: {
      type: 'string',
      'x-group': 'Advanced',
      'x-order': 30,
      'x-visibility': 'advanced',
      'x-display-hint': 'textarea',
      'x-help': 'JQ expression to map parent context to child initial context',
    },
    outputMapping: {
      type: 'string',
      'x-group': 'Advanced',
      'x-order': 31,
      'x-visibility': 'advanced',
      'x-display-hint': 'textarea',
      'x-help': 'JQ expression to map child final context back to parent',
    },
    maxRecursionDepth: {
      type: 'integer',
      minimum: 0,
      'x-group': 'Advanced',
      'x-order': 32,
      'x-visibility': 'advanced',
      'x-help': '0 = no recursion (default). N = allow N levels.',
    },
    groupId: {
      type: 'string',
      'x-group': 'Advanced',
      'x-order': 33,
      'x-visibility': 'advanced',
      'x-help': 'M-of-N grouping identifier',
    },
    totalInGroup: {
      type: 'integer',
      minimum: 1,
      'x-group': 'Advanced',
      'x-order': 34,
      'x-visibility': 'advanced',
    },
    requiredCount: {
      type: 'integer',
      minimum: 1,
      'x-group': 'Advanced',
      'x-order': 35,
      'x-visibility': 'advanced',
      'x-help': 'How many must complete to trigger threshold (default: totalInGroup)',
    },
    onThresholdReached: {
      type: 'string',
      enum: ['KEEP', 'CANCEL'],
      'x-group': 'Advanced',
      'x-order': 36,
      'x-visibility': 'advanced',
      'x-help': 'KEEP leaves remaining children running; CANCEL stops them',
    },
  },
} as const;
