import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  root: __dirname,
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        export: resolve(__dirname, 'export.html'),
      },
    },
  },
  resolve: {
    alias: [
      { find: '@casehubio/blocks-ui-core', replacement: resolve(__dirname, '../packages/blocks-ui-core/src') },
      { find: '@casehubio/blocks-ui-document-workbench', replacement: resolve(__dirname, '../components/document-workbench/src') },
      { find: '@casehubio/blocks-ui-work-item-row', replacement: resolve(__dirname, '../components/work-item-row/src') },
      { find: '@casehubio/blocks-ui-work-item-inbox', replacement: resolve(__dirname, '../components/work-item-inbox/src') },
      { find: '@casehubio/blocks-ui-work-item-detail', replacement: resolve(__dirname, '../components/work-item-detail/src') },
      { find: '@casehubio/blocks-ui-queue-board', replacement: resolve(__dirname, '../components/queue-board/src') },
      { find: '@casehubio/blocks-ui-work-item-workbench', replacement: resolve(__dirname, '../components/work-item-workbench/src') },
      { find: '@casehubio/blocks-ui-sla-indicator', replacement: resolve(__dirname, '../components/sla-indicator/src') },
      { find: '@casehubio/blocks-ui-kpi-metric-row', replacement: resolve(__dirname, '../components/kpi-metric-row/src') },
      { find: '@casehubio/blocks-ui-approval-gate', replacement: resolve(__dirname, '../components/approval-gate/src') },
      { find: '@casehubio/pages-table', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-table/src') },
      { find: '@casehubio/pages-primitives', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-primitives/src') },
      { find: '@casehubio/blocks-ui-notification-inbox', replacement: resolve(__dirname, '../components/notification-inbox/src') },
      { find: '@casehubio/blocks-ui-audit-trail-viewer', replacement: resolve(__dirname, '../components/audit-trail-viewer/src') },
      { find: '@casehubio/blocks-ui-trust-score-panel', replacement: resolve(__dirname, '../components/trust-score-panel/src') },
      { find: '@casehubio/blocks-ui-blocks-timeline', replacement: resolve(__dirname, '../components/blocks-timeline/src') },
      { find: '@casehubio/blocks-ui-channel-activity', replacement: resolve(__dirname, '../components/channel-activity/src') },
      { find: '@casehubio/blocks-ui-blocks-dag-viewer', replacement: resolve(__dirname, '../components/blocks-dag-viewer/src/blocks-dag-viewer.ts') },
      { find: '@casehubio/blocks-ui-blocks-decomposition-tree', replacement: resolve(__dirname, '../components/blocks-decomposition-tree/src/blocks-decomposition-tree.ts') },
      { find: '@casehubio/blocks-ui-blocks-plan-item-tree', replacement: resolve(__dirname, '../components/blocks-plan-item-tree/src/blocks-plan-item-tree.ts') },
      { find: '@casehubio/blocks-ui-blocks-plan-model-dashboard', replacement: resolve(__dirname, '../components/blocks-plan-model-dashboard/src/blocks-plan-model-dashboard.ts') },
      { find: '@casehubio/blocks-ui-execution-monitor', replacement: resolve(__dirname, '../components/execution-monitor/src') },
      { find: '@casehubio/blocks-ui-orchestration-workbench', replacement: resolve(__dirname, '../components/orchestration-workbench/src') },
      { find: '@casehubio/blocks-ui-contributor-workbench', replacement: resolve(__dirname, '../components/contributor-workbench/src') },
      { find: '@casehubio/blocks-ui-casehub-diagram', replacement: resolve(__dirname, '../components/casehub-diagram/src/casehub-diagram.ts') },
      { find: '@casehubio/blocks-ui-swf-diagram', replacement: resolve(__dirname, '../components/swf-diagram/src/swf-diagram.ts') },
      { find: '@casehubio/blocks-ui-org-diagram', replacement: resolve(__dirname, '../components/org-diagram/src/blocks-org-diagram.ts') },
      { find: '@casehubio/graph-stencil-org', replacement: resolve(__dirname, '../packages/graph-stencil-org/src') },
      { find: '@casehubio/blocks-ui-htn-diagram', replacement: resolve(__dirname, '../components/htn-diagram/src/htn-diagram.ts') },
      { find: '@casehubio/blocks-ui-diagram-workbench', replacement: resolve(__dirname, '../components/diagram-workbench/src/index.ts') },
      { find: '@tisoap/react-flow-smart-edge', replacement: resolve(__dirname, '../node_modules/@tisoap/react-flow-smart-edge/dist/index.mjs') },
      { find: '@casehubio/graph-stencil-htn', replacement: resolve(__dirname, '../packages/graph-stencil-htn/src') },
      { find: '@casehubio/graph-stencil-case', replacement: resolve(__dirname, '../packages/graph-stencil-case/src') },
      { find: '@casehubio/graph-stencil-swf', replacement: resolve(__dirname, '../packages/graph-stencil-swf/src') },
      { find: '@casehubio/pages-diagram-core', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-diagram-core/src') },
      { find: /^@casehubio\/graph-renderer\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/graph-renderer/src/$1') },
      { find: '@casehubio/graph-renderer', replacement: resolve(__dirname, '../.casehub-packages/packages/graph-renderer/src') },
      { find: '@drdreo/heatmap', replacement: resolve(__dirname, 'src/stubs/drdreo-heatmap.ts') },
      { find: '@casehubio/blocks-ui-split-workbench', replacement: resolve(__dirname, '../components/split-workbench/src') },
      { find: '@casehubio/blocks-ui-list-pane', replacement: resolve(__dirname, '../components/list-pane/src') },
      { find: '@casehubio/blocks-ui-detail-pane', replacement: resolve(__dirname, '../components/detail-pane/src') },
      { find: '@casehubio/blocks-ui-case-explorer', replacement: resolve(__dirname, '../components/case-explorer/src') },
      { find: '@casehubio/blocks-ui-case-dependency-graph', replacement: resolve(__dirname, '../components/case-dependency-graph/src') },
      { find: /^@casehubio\/graph-core\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/graph-core/src/$1') },
      { find: '@casehubio/graph-core', replacement: resolve(__dirname, '../.casehub-packages/packages/graph-core/src') },
      { find: '@casehubio/blocks-ui-routing-rationale', replacement: resolve(__dirname, '../components/routing-rationale/src') },
      { find: '@casehubio/blocks-ui-trust-feedback-display', replacement: resolve(__dirname, '../components/trust-feedback-display/src') },
      { find: '@casehubio/blocks-ui-trust-workbench', replacement: resolve(__dirname, '../components/trust-workbench/src') },
      { find: '@casehubio/blocks-ui-preferences-editor', replacement: resolve(__dirname, '../components/preferences-editor/src') },
      { find: '@casehubio/blocks-ui-session-list', replacement: resolve(__dirname, '../components/session-list/src') },
      { find: '@casehubio/blocks-ui-session-detail', replacement: resolve(__dirname, '../components/session-detail/src') },
      { find: '@casehubio/blocks-ui-session-workbench', replacement: resolve(__dirname, '../components/session-workbench/src') },
      { find: '@casehubio/agent-avatar-2d', replacement: resolve(__dirname, '../packages/agent-avatar-2d/src') },
      { find: '@casehubio/blocks-ui-agent-manifest-editor', replacement: resolve(__dirname, '../components/agent-manifest-editor/src') },
      { find: '@casehubio/blocks-ui-agent-catalog', replacement: resolve(__dirname, '../components/agent-catalog/src') },
      { find: '@casehubio/blocks-ui-agent-profile', replacement: resolve(__dirname, '../components/agent-profile/src') },
      { find: '@casehubio/blocks-ui-agent-relationship-editor', replacement: resolve(__dirname, '../components/agent-relationship-editor/src') },
      { find: /^@casehubio\/pages-viz\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/pages-viz/src/$1') },
      { find: '@casehubio/pages-viz', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-viz/src') },
      { find: '@casehubio/pages-ui-components', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-ui-components/src') },
      { find: /^@casehubio\/pages-ui-tokens\/dist\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/pages-ui-tokens/src/$1') },
      { find: '@casehubio/pages-ui-tokens', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-ui-tokens/src') },
      { find: /^@casehubio\/pages-component\/dist\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/pages-component/dist/$1') },
      { find: '@casehubio/pages-component', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-component/dist') },
      { find: /^@casehubio\/pages-data\/dist\/(.*)/, replacement: resolve(__dirname, '../.casehub-packages/packages/pages-data/src/$1') },
      { find: '@casehubio/pages-data', replacement: resolve(__dirname, '../.casehub-packages/packages/pages-data/src') },
      { find: /^react$/, replacement: resolve(__dirname, '../node_modules/react') },
      { find: /^react\/(.*)/, replacement: resolve(__dirname, '../node_modules/react') + '/$1' },
      { find: /^react-dom$/, replacement: resolve(__dirname, '../node_modules/react-dom') },
      { find: /^react-dom\/(.*)/, replacement: resolve(__dirname, '../node_modules/react-dom') + '/$1' },
      { find: 'lit', replacement: resolve(__dirname, '../node_modules/lit') },
      { find: 'lit/decorators.js', replacement: resolve(__dirname, '../node_modules/lit/decorators.js') },
      { find: '@lit/reactive-element', replacement: resolve(__dirname, '../node_modules/@lit/reactive-element') },
    ],
  },
  esbuild: {
    target: 'es2022',
    tsconfigRaw: JSON.stringify({
      compilerOptions: {
        experimentalDecorators: true,
        useDefineForClassFields: false,
      },
    }),
  },
  server: {
    port: 3000,
    open: true,
    hmr: { overlay: false },
    fs: {
      allow: ['..'],
    },
  },
});
