import type { SlaIndicatorProps } from '@casehubio/blocks-ui-sla-indicator';
import type { ExecutionMonitorProps } from '@casehubio/blocks-ui-execution-monitor';
import type { KpiMetricRowProps } from '@casehubio/blocks-ui-kpi-metric-row';
import type { ApprovalGateProps } from '@casehubio/blocks-ui-approval-gate';
import type { ServiceCardProps } from '@casehubio/blocks-ui-service-card';
import type { SlaBreachPolicyProps } from '@casehubio/blocks-ui-sla-breach-policy';
import type { TrustFeedbackDisplayProps } from '@casehubio/blocks-ui-trust-feedback-display';
import type { SimilarityPanelProps } from '@casehubio/blocks-ui-similarity-panel';
import type { ComplianceSummaryProps } from '@casehubio/blocks-ui-compliance-summary';
import type { GdprErasureActionProps } from '@casehubio/blocks-ui-gdpr-erasure-action';
import type { WorkItemRowProps } from '@casehubio/blocks-ui-work-item-row';
import type { DimensionDashboardProps } from '@casehubio/blocks-ui-dimension-dashboard';
import type { RoutingRationaleProps } from '@casehubio/blocks-ui-routing-rationale';
import type { TrustScorePanelProps } from '@casehubio/blocks-ui-trust-score-panel';
import type { GroupedDataViewProps } from '@casehubio/blocks-ui-grouped-data-view';
import type { AuditTrailViewerProps } from '@casehubio/blocks-ui-audit-trail-viewer';
import type { ListPaneProps } from '@casehubio/blocks-ui-list-pane';
import type { DetailPaneProps } from '@casehubio/blocks-ui-detail-pane';
import type { WorkItemInboxProps } from '@casehubio/blocks-ui-work-item-inbox';
import type { WorkItemDetailProps } from '@casehubio/blocks-ui-work-item-detail';
import type { WorkItemWorkbenchProps } from '@casehubio/blocks-ui-work-item-workbench';
import type { WorkerTaskPaneProps } from '@casehubio/blocks-ui-worker-task-pane';
import type { NotificationInboxProps, NotificationBellProps, SubscriptionEditorProps, NotificationPreferencesProps } from '@casehubio/blocks-ui-notification-inbox';
import type { ChannelActivityProps } from '@casehubio/blocks-ui-channel-activity';
import type { ConvergenceIndicatorProps, CommonGroundPanelProps, ConversationWorkbenchProps, PointListProps, PointDetailProps } from '@casehubio/blocks-ui-conversation-viewer';
import type { CaseExplorerProps, EntityListProps, EntityDetailProps, EntityTreeProps } from '@casehubio/blocks-ui-case-explorer';
import type { OrchestrationWorkbenchProps } from '@casehubio/blocks-ui-orchestration-workbench';
import type { DagViewerProps } from '@casehubio/blocks-ui-blocks-dag-viewer';
import type { DecompositionTreeProps } from '@casehubio/blocks-ui-blocks-decomposition-tree';
import type { PlanItemTreeProps } from '@casehubio/blocks-ui-blocks-plan-item-tree';
import type { PlanModelDashboardProps } from '@casehubio/blocks-ui-blocks-plan-model-dashboard';
import type { CaseFlowViewerProps } from '@casehubio/blocks-ui-case-flow-viewer';
import type { CaseDependencyGraphProps } from '@casehubio/blocks-ui-case-dependency-graph';
import type { DiagramWorkbenchProps } from '@casehubio/blocks-ui-diagram-workbench';
import type { ClusterPanelProps } from '@casehubio/blocks-ui-cluster-panel';
import type { ReconciliationStatusProps } from '@casehubio/blocks-ui-reconciliation-status';
import type { TopologyViewerProps } from '@casehubio/blocks-ui-topology-viewer';
import type { SessionListProps } from '@casehubio/blocks-ui-session-list';
import type { SessionDetailProps } from '@casehubio/blocks-ui-session-detail';
import type { SessionWorkbenchProps } from '@casehubio/blocks-ui-session-workbench';
import type { PreferencesEditorProps } from '@casehubio/blocks-ui-preferences-editor';
import type { TrustWorkbenchProps } from '@casehubio/blocks-ui-trust-workbench';
import type { ContributorWorkbenchProps } from '@casehubio/blocks-ui-contributor-workbench';
import type { CommitmentRangeBarProps, CommitmentTransitionBadgeProps } from '@casehubio/blocks-ui-commitment-viz';
import type { OrgDiagramProps } from '@casehubio/blocks-ui-org-diagram';
import type { DenyPatternEditorProps, WatchPatternEditorProps, GatePolicyEditorProps, EvolutionStreamsProps, EvolutionInboxProps } from '@casehubio/blocks-ui-evolution-config';
import type { EvolutionWorkbenchProps } from '@casehubio/blocks-ui-evolution-workbench';
import type { AgentDetailProps } from '@casehubio/blocks-ui-agent-detail';

export interface BlocksComponentRegistry {
  'blocks-sla-indicator': SlaIndicatorProps;
  'blocks-execution-monitor': ExecutionMonitorProps;
  'blocks-kpi-metric-row': KpiMetricRowProps;
  'blocks-approval-gate': ApprovalGateProps;
  'blocks-service-card': ServiceCardProps;
  'blocks-sla-breach-policy': SlaBreachPolicyProps;
  'blocks-trust-feedback-display': TrustFeedbackDisplayProps;
  'blocks-similarity-panel': SimilarityPanelProps;
  'blocks-compliance-summary': ComplianceSummaryProps;
  'blocks-gdpr-erasure-action': GdprErasureActionProps;
  'blocks-work-item-row': WorkItemRowProps;
  'blocks-dimension-dashboard': DimensionDashboardProps;
  'blocks-routing-rationale': RoutingRationaleProps;
  'blocks-trust-score-panel': TrustScorePanelProps;
  'blocks-grouped-data-view': GroupedDataViewProps;
  'blocks-audit-trail-viewer': AuditTrailViewerProps;
  'blocks-list-pane': ListPaneProps;
  'blocks-detail-pane': DetailPaneProps;
  'blocks-work-item-inbox': WorkItemInboxProps;
  'blocks-work-item-detail': WorkItemDetailProps;
  'blocks-work-item-workbench': WorkItemWorkbenchProps;
  'blocks-worker-task-pane': WorkerTaskPaneProps;
  'blocks-notification-inbox': NotificationInboxProps;
  'blocks-notification-bell': NotificationBellProps;
  'blocks-subscription-editor': SubscriptionEditorProps;
  'blocks-notification-preferences': NotificationPreferencesProps;
  'blocks-channel-activity': ChannelActivityProps;
  'blocks-convergence-indicator': ConvergenceIndicatorProps;
  'blocks-common-ground-panel': CommonGroundPanelProps;
  'blocks-conversation-workbench': ConversationWorkbenchProps;
  'blocks-point-list': PointListProps;
  'blocks-point-detail': PointDetailProps;
  'blocks-case-explorer': CaseExplorerProps;
  'blocks-entity-list': EntityListProps;
  'blocks-entity-detail': EntityDetailProps;
  'blocks-entity-tree': EntityTreeProps;
  'blocks-orchestration-workbench': OrchestrationWorkbenchProps;
  'blocks-dag-viewer': DagViewerProps;
  'blocks-decomposition-tree': DecompositionTreeProps;
  'blocks-plan-item-tree': PlanItemTreeProps;
  'blocks-plan-model-dashboard': PlanModelDashboardProps;
  'blocks-case-flow-viewer': CaseFlowViewerProps;
  'blocks-case-dependency-graph': CaseDependencyGraphProps;
  'blocks-diagram-workbench': DiagramWorkbenchProps;
  'blocks-cluster-panel': ClusterPanelProps;
  'blocks-reconciliation-status': ReconciliationStatusProps;
  'blocks-topology-viewer': TopologyViewerProps;
  'blocks-session-list': SessionListProps;
  'blocks-session-detail': SessionDetailProps;
  'blocks-session-workbench': SessionWorkbenchProps;
  'blocks-preferences-editor': PreferencesEditorProps;
  'blocks-trust-workbench': TrustWorkbenchProps;
  'blocks-contributor-workbench': ContributorWorkbenchProps;
  'commitment-range-bar': CommitmentRangeBarProps;
  'commitment-transition-badge': CommitmentTransitionBadgeProps;
  'blocks-org-diagram': OrgDiagramProps;
  'blocks-deny-pattern-editor': DenyPatternEditorProps;
  'blocks-watch-pattern-editor': WatchPatternEditorProps;
  'blocks-gate-policy-editor': GatePolicyEditorProps;
  'blocks-evolution-workbench': EvolutionWorkbenchProps;
  'blocks-evolution-streams': EvolutionStreamsProps;
  'blocks-evolution-inbox': EvolutionInboxProps;
  'blocks-agent-detail': AgentDetailProps;
}
